### ISSUE TITLE
Attributes which end with question mark break #inspect method

### ISSUE THREAD

**Issue by mblumtritt** [mmainz/valued#2]
The `#inspect` method raises an error when attributes with question mark at the end like in `foo.active?` is defined.

Sample:

```ruby
class Foo
   include Valued

   attribute :active?
end

p Foo.new

```

**Comment by mmainz** [comment]
Hmm, yes. I looked at this and came to the conclusion that we are better of without this feature. If you really need it, you could always define a method inside your class.

I already released the removal as 0.4.0.
