### ISSUE TITLE
Value of attribute cannot be set to `nil` via `#update`

### ISSUE THREAD

**Issue by mwannewitz** [mmainz/valued#6]
When calling `update` on a Valued object and passing `nil` as a new value, it is not set to `nil` but instead remains at the current value

```ruby
class Quantity
  include Valued

  attributes :unit, :amount
end
```
```ruby
quantity = Quantity.new(unit: 'kg', amount: 1)
=> #<Quantity unit="kg" amount=1>
quantity.update(amount: nil)
=> #<Quantity unit="kg" amount=1>
```

I would expect that I can set the value to `nil`.

**Comment by mmainz** [comment]
Hmm, yes, this sucks. If you want it fixed fast, I'd suggest you make a pull request fixing this. I don't know when I'll have time to work on this.
